services:
  # 1. Наша база даних всередині Render
  - type: database
    name: diploma-db
    plan: free
    databaseName: feellikeevent_db
    user: sofia_admin

  # 2. Бекенд (FastAPI)
  - type: web
    name: diploma-backend
    plan: free
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: diploma-db
          property: connectionString
      # Додайте сюди інші змінні з вашого .env, наприклад:
      - key: GOOGLE_CLIENT_ID
        value: ваш_id_з_google_console

  # 3. Парсер сервіс (Private - закритий від інтернету)
  - type: pservice
    name: diploma-parser
    plan: free
    runtime: docker
    dockerContext: ./parser-service
    dockerfilePath: ./parser-service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: diploma-db
          property: connectionString

  # 4. Фронтенд (Angular / Ionic)
  - type: web
    name: feellikeevent # це ім'я сформує ваш URL: feellikeevent.onrender.com
    plan: free
    runtime: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: diploma-backend
          property: host