[pytest]
testpaths = tests
filterwarnings =
    ignore:Support for class-based `config` is deprecated:DeprecationWarning
    ignore:pkg_resources is deprecated as an API:UserWarning
    ignore:websockets\.client\.connect is deprecated:DeprecationWarning
    ignore:websockets\.legacy is deprecated:DeprecationWarning
